[tool.poetry]
name = "typegen"
version = "0.1.0"
description = ""
authors = ["Thomas Staats <thomas.staats443@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
